name: .NET Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # change to your .NET version

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore EvBackend.sln

      # Build the project
      - name: Build
        run: dotnet build EvBackend.sln --no-restore --configuration Release

      # Run tests
      - name: Run tests
        run: dotnet test EvBackend.sln --no-build --verbosity normal
