name: .NET Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # or your project version

      - name: Change directory to EvBackend
        run: cd EvBackend

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore EvBackend.sln

      # Build the solution
      - name: Build solution
        run: dotnet build EvBackend.sln --configuration Debug --no-restore

      # Run tests
      - name: Run unit tests
        run: dotnet test EvBackend.Tests/EvBackend.Tests.csproj --no-build --verbosity normal
